global_options:
  floor_generator:
    runs_before:
      - riverpod_generator
  freezed:
    runs_before:
      - floor_generator
      - riverpod_generator
      - retrofit_generator
      - json_serializable
  json_serializable:
    runs_before:
      - floor_generator
      - retrofit_generator

  